services:
  api:
    build: backend
    restart: always
    environment:
      SERVER_NAME: ${BOZUDON_SERVER_NAME}
      SERVER_URL: ${BOZUDON_SERVER_URL}
      CLIENT_URL: ${BOZUDON_CLIENT_URL}
      DB_HOST: ${BOZUDON_DB_HOST}
      DB_PORT: ${BOZUDON_DB_PORT}
      DB_NAME: ${BOZUDON_DB_NAME}
      DB_USER: ${BOZUDON_DB_USER}
      DB_PW: ${BOZUDON_DB_PW}
      RUST_LOG: info
    depends_on:
      - db

  web:
    build: frontend
    restart: always
    environment:
      SERVER_URL: http://api:8080
      CLIENT_URL: ${BOZUDON_CLIENT_URL}
      CLIENT_ID: ${BOZUDON_CLIENT_ID}
      CLIENT_SECRET: ${BOZUDON_CLIENT_SECRET}
      REDIRECT_URI: ${BOZUDON_AUTH_CALLBACK_URL}
      NEXT_PUBLIC_SERVER_URL: ${BOZUDON_SERVER_URL}
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${BOZUDON_DB_NAME}
      POSTGRES_USER: ${BOZUDON_DB_USER}
      POSTGRES_PASSWORD: ${BOZUDON_DB_PW}

  lb:
    image: nginx:latest
    ports:
    - 8080:80
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres:
