//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod account;
pub mod app;
pub mod favorite;
pub mod follow;
pub mod media;
pub mod oauth_access_grant;
pub mod oauth_access_token;
pub mod status;
pub mod user;
