//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::account::Entity as Account;
pub use super::app::Entity as App;
pub use super::favorite::Entity as Favorite;
pub use super::follow::Entity as Follow;
pub use super::media::Entity as Media;
pub use super::oauth_access_grant::Entity as OauthAccessGrant;
pub use super::oauth_access_token::Entity as OauthAccessToken;
pub use super::status::Entity as Status;
pub use super::user::Entity as User;
